### ISSUE TITLE
queueBuffer: BufferQueue has been abandoned

### ISSUE THREAD

**Issue by buelersandra** [natario1/CameraView#103]
how to prevent "queueBuffer: BufferQueue has been abandoned" when view is dismissed from screen without taking a picture after cameraview.Start() is called.

**Comment by natario1** [comment]
I don't know what that means

**Comment by buelersandra** [comment]
<img width="627" alt="screen shot 2017-11-15 at 5 23 35 pm" src="https://user-images.githubusercontent.com/11475652/32850396-ea277528-ca29-11e7-9897-de08734d5216.png">

**Comment by natario1** [comment]
It's because we release stuff asynchronously (e.g. not exactly `onStop` but some moments later). See this very good answer: https://stackoverflow.com/a/22490648/4288782 .

We release the camera *moments after* the surface has been destroyed, and that's where you get that warning, until the camera is destroyed too. I think we can safely ignore it.
