### ISSUE TITLE
ImageFormat Condition always false

### ISSUE THREAD

**Issue by microcian** [natario1/CameraView#1032]
Please let me know the why format always return to me 35 while the condition is on 17
frame.format == ImageFormat.NV21 while frame.format having 35 value and ImageFormat.NV21 is 17, I'm using Samsung S9

**Comment by EzequielAdrianM** [comment]
35 is the Constant Value. (0x00000027) which corresponds to YUV_422_888

**Comment by microcian** [comment]
Yeah I know, but my point is your "if" condition only handling NV21 case, you didn't handle any other case in cameraActivity -> frameProcessor
In my case, I wrote else part and I'm getting a blank image, please look into it

val data = frame.getData<Image>()
                                val stream = ByteArrayOutputStream()
                                val bmp = Bitmap.createBitmap(data.width, data.height, Bitmap.Config.ARGB_8888)
                                bmp.compress(Bitmap.CompressFormat.PNG, 100, stream)
                                val byteArray = stream.toByteArray()

 frame.getData<Image> rather than frame.getData<ByteArray>() because of I'm receiving Image from camera

**Comment by microcian** [comment]
When I Convert YUV_420_888 to NV21, I'm getting the following error

  java.lang.IllegalArgumentException: only support ImageFormat.NV21 and ImageFormat.YUY2 for now

**Comment by EzequielAdrianM** [comment]
I don't know what task you need to perform with the camera frames, but (i guess) you want to perform face detection. According to the [Google Vision Documentation](https://developers.google.com/android/reference/com/google/android/gms/vision/Frame.Builder#setImageData(java.nio.ByteBuffer,%20int,%20int,%20int)), the frame processor supports camera frames in: [NV16](https://developer.android.com/reference/android/graphics/ImageFormat.html#NV16), [NV21](https://developer.android.com/reference/android/graphics/ImageFormat.html#NV21) and [YV12](https://developer.android.com/reference/android/graphics/ImageFormat.html#YV12) format. For the sake of simplicity, i just recommend to stick with the Camera1 API only (exclude camera2) because Camera1 will **always** output NV21 frames which the detector will handle without problems.

Please also note that face detector also supports camera frames in Bitmap format, through [setBitmap()](https://developers.google.com/android/reference/com/google/android/gms/vision/Frame.Builder#setBitmap(android.graphics.Bitmap)) method instead of setImageData().

Anyways, if you still want to use the Camera2 API, through the Bytes approach, you will need to convert the [YUV_420_888.](https://developer.android.com/reference/android/graphics/ImageFormat#YUV_420_888) image to NV21.

According to the docs, YUV_420_888 is:

> /**
     * Multi-plane Android YUV 420 format
     * This format is a generic YCbCr format, capable of describing any 4:2:0 chroma-subsampled
     * planar or semiplanar buffer (but not fully interleaved), with 8 bits per color sample.
     * Images in this format are always represented by three separate buffers of data, one for
     * each color plane. Additional information always accompanies the buffers, describing the
     * row stride and the pixel stride for each plane.
     * */
   

**Here the solution:**
```
private byte[] convertYUV420888ToNV21(Image imgYUV420) {
        // Converting YUV_420_888 data to NV21.
        byte[] data;
        ByteBuffer y = imgYUV420.getPlanes()[0].getBuffer();
        ByteBuffer cb = imgYUV420.getPlanes()[2].getBuffer();
        int buffer0_size = y.remaining();
        int buffer2_size = cb.remaining();
        data = new byte[buffer0_size + buffer2_size];
        y.get(data, 0, buffer0_size);
        cb.get(data, buffer0_size, buffer2_size);
        return data;
 }
```

```
// These pending variables hold the state associated with the new frame awaiting processing.
private long mPendingTimeMillis;
private final long mStartTimeMillis = SystemClock.elapsedRealtime();
private int mPendingFrameId = 0;
cameraView.addFrameProcessor(frame -> {
	mPendingTimeMillis = SystemClock.elapsedRealtime() - mStartTimeMillis;
	mPendingFrameId++;
	int frameFormat = frame.getFormat();
	if(frameFormat == ImageFormat.YUV_420_888) {
		Size size = frame.getSize();
		com.google.android.gms.vision.Frame outputFrame = null;
		Image data = frame.getData();
		outputFrame = new com.google.android.gms.vision.Frame.Builder()
                    .setImageData(ByteBuffer.wrap(convertYUV420888ToNV21(data)), size.getWidth(), size.getHeight(), ImageFormat.NV21)
                    .setId(mPendingFrameId)
                    .setTimestampMillis(mPendingTimeMillis)
                    .setRotation(getDetectorOrientation(frame.getRotationToUser()))
                    .build();
                previewFaceDetector.receiveFrame(outputFrame);
                data.close();
	}
});
```

**You'll also need this:**

```
private int getDetectorOrientation(int sensorOrientation) {
    switch (sensorOrientation) {
        case 0:
        case 360:
            return com.google.android.gms.vision.Frame.ROTATION_0;
        case 90:
            return com.google.android.gms.vision.Frame.ROTATION_90;
        case 180:
            return com.google.android.gms.vision.Frame.ROTATION_180;
        case 270:
            return com.google.android.gms.vision.Frame.ROTATION_270;
    }
    return com.google.android.gms.vision.Frame.ROTATION_90;
}
```

Code was taken from my [Camera2Vision](https://github.com/EzequielAdrianM/Camera2Vision) repository.
