### ISSUE TITLE
Add support for custom camera engines

### ISSUE THREAD

**Issue by ObsidianX** [natario1/CameraView#1069]
### Problem to be addressed
Allow apps to supply their own CameraEngine implementations to support alternative camera sources such as USB cameras, videos, streaming sources, etc.

### Describe the solution you'd like
Add an API to provide a custom CameraEngine implementation.

**Comment by natario1** [comment]
This has always been possible, just through a different mechanism - you subclass CameraView and override instantiateCameraEngine. You'll get the callbacks as well. Is there anything else that you'd need?

Direct API is easier, but it's like me and you using it, I prefer that an advanced use case like this has an advanced implementation path as well, since using CameraEngine requires familiarity with the source code.

**Comment by ObsidianX** [comment]
Ah gotcha, that should work just fine. Thanks!
