### ISSUE TITLE
Capture Documents

### ISSUE THREAD

**Issue by aliakkawi** [natario1/CameraView#123]
I am using this Repository for capturing images for documents (papers). When the paper is on a table for example, i mean the device is set horizontally above the table (device set to down), the preview image is Flipped, please advice me how to fix the issue. Thanks

**Comment by natario1** [comment]
Does it happen with 1.4.0?

**Comment by aliakkawi** [comment]
I am not sure, actually what i need is to capture an image for a Bank Cheque that is set on a table (the device camera should point to bottom  please check the attached images. Thanks a lot.
![whatsapp image 2017-12-13 at 20 42 15](https://user-images.githubusercontent.com/14969941/33956628-d4c365aa-e047-11e7-9897-9c962a89ddc1.jpeg)
![whatsapp image 2017-12-14 at 20 42 15](https://user-images.githubusercontent.com/14969941/33956629-d4e79254-e047-11e7-8a1a-c408897283c0.jpeg)

 ).

**Comment by aliakkawi** [comment]
I am using the latest update 1.4.1

**Comment by natario1** [comment]
If this is about the result, I think we can't do anything about phones in a horizontal plane position, we treat them as having screen orientation == 0, e.g. the screen natural orientation. So the result picture might be flipped with respect to what you expect. 

If this is about the preview, then it's not clear to me what the bug is. Please try to restrict the bug to a non-horizontal situation, so we can understand better what's better. The horizontal device adds confusion to this. You can open a new one. Thanks!
