### ISSUE TITLE
When orientation is locked by XML, camera orientation is still able to change

### ISSUE THREAD

**Issue by guness** [natario1/CameraView#171]
- [x] *I am using the latest version*
- [x] *I can reproduce the bug in the demo app, and if not...*
- [x] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

This is rather a question than a bug.
Whan I lock the orientation of the camera activity by
```
<activity
            android:name=".ui.record.RecordActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="landscape"
            android:theme="@style/FullscreenTheme" />
```
I would expect camera orientation is also locked, however when I start recording video portrait, the output is also portrait and vice versa regardless of the activity orientation. I was not able to find a method to set(or lock) orientation manually as well. 

I like this smart feature, however requirement on my current work forces me to have a locked video orientation. So I am humbly asking if this is possible?

#### Screenshots:

![screen](https://user-images.githubusercontent.com/16373485/36836861-99954e12-1d4b-11e8-88b5-ade33e949adc.png)

**Comment by natario1** [comment]
There is no such method, if you start recording holding the phone in landscape, we will respect that orientation (no matter the activity orientation).

If we didn't do that, your video would appear rotated (for example, sky in the left/bottom part instead of top). If you wish, you can rotate the video afterwards using some other tool.

**Comment by guness** [comment]
Got it thanks!
