### ISSUE TITLE
Control preview FPS?

### ISSUE THREAD

**Issue by athornz** [natario1/CameraView#220]
Is it possible to set the desired FPS for the camera preview?

I'm implementing live frame processing and I don't need the full 30 fps.

**Comment by natario1** [comment]
Is it possible I think, but we offer no API for that. Feel free to work on it!

**Comment by natario1** [comment]
I think you can just use `Thead.sleep()` inside the process method to slow things down. But I don't think we can offer exact FPS, because the frame dispatching depends on the time you spend in your `process()` method.

So, it might look like an hack but I think the best way to receive less frames is just sleep there.
