### ISSUE TITLE
Setting parameters while camera is restarting (for example right after setFacing)

### ISSUE THREAD

**Issue by freimaks** [natario1/CameraView#31]
Hello!

I found another error. Maybe it's a library error.

An error occurs if we try to switch the HDR or white balance.

I do as you said before:
1. camera.stop();
2. Set the settings (front or back, grid, quality, etc.)
3. camera.start();

Everything works fine if we not use setHDR or setWhiteBalance. It does not matter where we apply the settings (before the camera.start() or after). Using these two settings in onResume does not cause errors.

Here are two pictures with errors:
1. For HDR:
![image](https://user-images.githubusercontent.com/26241659/30076632-2c88b4c0-9282-11e7-81b4-7723a7ea73f0.png)

2. For WhiteBalance:
![image](https://user-images.githubusercontent.com/26241659/30076555-e150d2b2-9281-11e7-84fa-08ba223930fc.png)

**Comment by natario1** [comment]
Yeah I can see why this happens. I'll fix this!

**Comment by natario1** [comment]
I will consider this low-priority though, because I do not recommended acting this way.

`camera.stop()` and `camera.start()` are not synchronous, and they will be even less so with Camera2.
The correct approach after calling `stop()` is to wait for `onCameraClosed()` to be called, and then start again and/or set parameters.

```java
CameraListener close = new CameraListener() { /* ... listen to onCameraClosed() */ };
camera.addListener(new CameraListener() {
    @Override
    public void onCameraClose() {
        camera.removeListener(this);
        // Set parameters and start again.
        camera.start();
    }
});
camera.stop();
```

Plus, **if all you want is change Facing**, you can call `setFacing()` while the preview is active and the library will manage this for you. Then wait for `onCameraOpened` before changing params.

**Comment by ManueGE** [comment]
If I remove listener from `onCameraClose` method, I get a crash:

```
   java.util.ConcurrentModificationException
```

Any other idea?

**Comment by natario1** [comment]
It's a bug, can you open a new issue @ManueGE ?

**Comment by ManueGE** [comment]
Sure, I will @natario1 . 

Thanks :)
