### ISSUE TITLE
Access denied finding property "camera.hal1.packagelist"

### ISSUE THREAD

**Issue by Anikeshpatel** [natario1/CameraView#341]
W/CameraViewContr: type=1400 audit(0.0:51835): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=5417 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
I/zygote64: Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()
E/libc: Access denied finding property "camera.hal1.packagelist"
W/CameraViewContr: type=1400 audit(0.0:51836): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=5417 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0

**Comment by dnhyde** [comment]
This still happens on some devices (Xiaomi Redmi 5 plus here)

**Comment by crifan** [comment]
the error 

`E/libc: Access denied finding property "camera.hal1.packagelist"`

is caused by previous warning:

`W/CameraViewContr: type=1400 audit(0.0:51835): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=5417 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
I/zygote64: Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()`

more detailed explanation can refer [another post's answer](https://stackoverflow.com/questions/59533551/access-denied-finding-property-persist-vendor-log-tel-dbg/63259127#63259127)
