### ISSUE TITLE
VideoBitRate stays on default after modification.

### ISSUE THREAD

**Issue by romrozen** [natario1/CameraView#406]
### Describe the bug

Changing the video bitrate with the method 'setVideoBitRate' or in xml (cameraVideoBitRate) has no affect on the produced file quality or size.

- CameraView version: *2.0.0-beta04*
- Device / Android version: *OnePlus 3t, API 28*

### To Reproduce
1.Change the bitrate of the CameraView object, either through XML or the JAVA method.
1. Check file size or quality after capture.

### Expected behavior
Quality changes, file reduced (if short bit rate is chosen)

**Comment by natario1** [comment]
We simply pass this value to `MediaRecorder.setVideoBitRate`:

/**
     * Sets the video encoding bit rate for recording. Call this method before prepare().
     * Prepare() may perform additional checks on the parameter to make sure whether the
     * specified bit rate is applicable, and sometimes the passed bitRate will be
     * clipped internally to ensure the video recording can proceed smoothly based on
     * the capabilities of the platform.
     *
     * @param bitRate the video encoding bit rate in bits per second.
     */

So there's nothing else that we can do. Also since frame rate is fixed & resolution is fixed I'm not sure if the bitRate could change the results... It's probably being ignored. Can you try changing the frameRate and see if the result changes?
