### ISSUE TITLE
onRequestPermissionsResult() is getting called in the loop.

### ISSUE THREAD

**Issue by malikmotani** [natario1/CameraView#479]
### Description
After **DENY** camera and audio permission with **Don't ask again**, `onRequestPermissionsResult()` is getting called in the loop.

- CameraView version: *2.0.0-beta05*
- Reproducible in official demo app: yes
- Device / Android version: *OnePlus5t, API 28 & Moto G4 Plus, API 26*

### To Reproduce
Steps to reproduce the behaviour, possibly in the demo app:
1. Open the official demo app
2. In CameraActivity monitor `onRequestPermissionsResult()` after **DENY** camera and audio permission with **Don't ask again**

### Expected behaviour
A ration dialog for required permissions and app settings redirection.

### Logs
After setting logs `CameraLogger.setLogLevel(LEVEL_VERBOSE)` I'm getting below logs in the loop.

> CameraController: Stop: posting runnable. State: STATE_STOPPED
> CameraController: Stop: executing. State: STATE_STOPPED

**Comment by daniestrella1** [comment]
Thats because you're calling open() (v2) or start() (v1) methods in onResume. When the request dialog permission finishes, Android calls automatically onResume method again which would once again display the dialog and cause an endless cycle.

Consider keeping or check the status of the permissions before to determine if must call open()/start() method.
